### PR TITLE
Add gather contracts

### PR DESCRIPTION
**Pull request by scream4ik**
- Depends on https://github.com/gnosis/gnosis-py/pull/142
- Depends on https://github.com/gnosis/safe-deployments/pull/39

### CODE REVIEW

**Comment by Uxio0** [comment]
I will merge this when the other issues are merged, please ping me back then 😉

**Comment by Uxio0** [comment]
Could you update `gnosis-py==3.7.1` in `requirements.txt`?

**Comment by scream4ik** [comment]
done)

**Review by Uxio0 — APPROVED** [review]

**Comment by Uxio0** [comment]
I'm reverting this PR as by mistake I didn't see that https://github.com/gnosis/safe-deployments/pull/39 was not merged , and we only support contracts merged there

**Pull request merged**
