### PR TITLE
Support metis contracts

### PR DESCRIPTION
**Pull request by titandac**
### What was wrong?
Would you consider upstreaming this change. It would save the Metis team from having to maintain a fork of this repo.
Closes #

### How was it fixed?

@gnosis/safe-services

### CODE REVIEW

**Comment by titandac** [comment]
https://github.com/gnosis/gnosis-py/pull/162
https://github.com/gnosis/safe-deployments/pull/53

**Comment by titandac** [comment]
recheck

**Comment by titandac** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by titandac** [comment]
> I'm only merging the changes to `safe_transaction_service/history/management/commands/setup_service.py`, please revert all the other changes and rebase `master` branch

Hey sorry about that. Looks like I forgot about this PR and pushed some extra changes to it.

**Comment by Uxio0** [comment]
Formatting tests are not passing, please make sure you run the pre-commit hooks: https://github.com/gnosis/safe-transaction-service#setup-for-development

**Comment by Uxio0** [comment]
Hi, just a reminder as I see this PR has not been active for 19 days 😉

**Comment by titandac** [comment]
couldn't get time to update this until now, thank you for waiting. 

rebased against master and passed the pre-commit hooks.

**Review by Uxio0 — APPROVED** [review]

**Pull request merged**
