### PR TITLE
chore: add rei testnet and mainnet

### PR DESCRIPTION
**Pull request by bijianing97**
### What was wrong?

New custom chain

### How was it fixed?

Deploy contracts, add addresses here.

### CODE REVIEW

**Comment by bijianing97** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Uxio0** [comment]
Ok, I see that you deployed the contracts: https://github.com/gnosis/safe-deployments/pull/70 . Can you update https://github.com/gnosis/safe-transaction-service/blob/master/requirements.txt#L24 to `3.9.2`?

**Comment by bijianing97** [comment]
> Ok, I see that you deployed the contracts: [gnosis/safe-deployments#70](https://github.com/gnosis/safe-deployments/pull/70) . Can you update https://github.com/gnosis/safe-transaction-service/blob/master/requirements.txt#L24 to `3.9.2`?

Yes sir, did you mean in this pull request I should change the `gnosis-py[django]` to `3.9.2` in the requirements.txt ?

**Comment by bijianing97** [comment]
> > Yes sir, did you mean in this pull request I should change the `gnosis-py[django]` to `3.9.2` in the requirements.txt ? I never tried it for deployment
> 
> Yes, as the networks don't exist in the current version of `gnosis-py`, so it breaks the tests. `gnosis-py==3.9.2` is still not available but will be soon

OK sir, I have changed it, please check it again, thanks.

**Comment by bijianing97** [comment]
@Uxio0 Hello, can you please merge this PR so we can continue work in our side, we can see gnosis-py@3.9.2 is ready at this time

**Comment by lanhaoxiang** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by Uxio0 — APPROVED** [review]

**Pull request merged**
