### PR TITLE
Add shyft testnet contract addresses for service setup

### PR DESCRIPTION
**Pull request by svanegmond**
### What was wrong?

New custom chain

### How was it fixed?

Deploy contracts, add addresses here.

### CODE REVIEW

**Comment by rmeissner** [comment]
This depends on https://github.com/gnosis/safe-deployments/pull/68

**Comment by svanegmond** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by svanegmond** [comment]
CLA exception is right, but I am the committer... 'root' was a mistake owing to a bad choice of user at time of commit.
Can anyone kick this through or do I have to reformulate?

**Comment by Uxio0** [comment]
> CLA exception is right, but I am the committer... 'root' was a mistake owing to a bad choice of user at time of commit. Can anyone kick this through or do I have to reformulate?

Yes please, if you can rebase and force push it again it will be awesome. CLA can not be disabled

**Review by Uxio0 — APPROVED** [review]

**Comment by Uxio0** [comment]
Still conflicting

**Pull request merged**
